// Auto-generated by @nostrability/schemata-codegen
// Do not edit manually.
//
// Generated from 155 tag schemas
/**
 * protectedTag
 *
 * Protected event tag ("-"). The tag name is a single dash character, indicating the event is only meant to be consumed by the relay it was published to.
 */
export type ProtectedTag = readonly ["-"];

export type UpperATag = readonly ["a", string, string, ...string[]];

export type ALiveTag = readonly ["a", string, string, ...string[]];

export type ARoomTag = readonly ["a", string, string, ...string[]];

export type ATag = readonly ["a", string, string, ...string[]];

export type Accessed_onTag = readonly ["accessed_on", string];

export type AmountTag = readonly ["amount", string];

export type AmtTag = readonly ["amt", string];

export type AppliedAsCommitsTag = readonly ["applied-as-commits", string, ...string[]];

export type AuthorTag = readonly ["author", string, ...string[]];

export type BidTag = readonly ["bid", string];

/**
 * Blurhash placeholder for the encrypted media
 */
export type BlurhashTag = readonly ["blurhash", string];

export type Bolt11Tag = readonly ["bolt11", string];

export type BranchNameTag = readonly ["branch-name", string];

export type CTag = readonly ["c", string];

/**
 * Authentication challenge provided by the relay
 */
export type ChallengeTag = readonly ["challenge", string];

export type Chapter_titleTag = readonly ["chapter_title", string];

export type ClaimTag = readonly ["claim", string];

export type ClientTag = readonly ["client", string, string, string];

export type Mls_clientTag = readonly ["client", string, ...string[]];

/**
 * Git clone endpoints
 */
export type CloneTag = readonly ["clone", string, ...string[]];

export type CodeTag = readonly ["code", string];

export type CommentTag = readonly ["comment", string];

export type CommitTag = readonly ["commit", string];

export type CommitPgpSigTag = readonly ["commit-pgp-sig", "" | string];

export type CommitterTag = readonly ["committer", string, string, string, string];

/**
 * Content warning tag (NIP-36). Optional reason as second element.
 */
export type ContentWarningTag =
  | readonly ["content-warning"]
  | readonly ["content-warning", string];

export type ContextTag = readonly ["context", string];

export type Current_participantsTag = readonly ["current_participants", string, ...string[]];

export type DTag = readonly ["d", string, ...string[]];

export type StatusTypeTag = readonly ["d", string, ...string[]];

/**
 * Key required to decrypt the encrypted file
 */
export type DecryptionKeyTag = readonly ["decryption-key", string];

/**
 * Nonce required alongside the decryption key
 */
export type DecryptionNonceTag = readonly ["decryption-nonce", string];

export type DescriptionTag = readonly ["description", string];

/**
 * Image dimensions in the form <width>x<height>
 */
export type DimTag = readonly ["dim", string];

export type DoiTag = readonly ["doi", string];

export type UpperETagVariant1 =
  | readonly ["e", string, string | "", "reply" | "root"]
  | readonly ["e", string, string | "", "reply" | "root", string];
export type UpperETagVariant2 =
  | readonly ["e", string]
  | readonly ["e", string, string];
export type UpperETag = UpperETagVariant1 | UpperETagVariant2;

export type ERedeemedTag = readonly ["e", string, string, "redeemed"];

/**
 * Reference to the root patch or issue event
 */
export type ERootTag = readonly ["e", string, "" | string, "root"];

/**
 * Reference to an accepted revision root event
 */
export type EStatusReplyTag = readonly ["e", string, "" | string, "reply"];

export type ETagVariant1 =
  | readonly ["e", string, string | "", "reply" | "root"]
  | readonly ["e", string, string | "", "reply" | "root", string];
export type ETagVariant2 =
  | readonly ["e", string]
  | readonly ["e", string, string];
export type ETag = ETagVariant1 | ETagVariant2;

export type Nip56_eTag = readonly ["e", string, "nudity" | "malware" | "profanity" | "illegal" | "spam" | "impersonation" | "other", ...string[]];

/**
 * reactionETag
 *
 * Event reference tag for reaction events (NIP-25)
 */
export type ReactionETag = readonly ["e", string, ...string[]];

export type EditorTag = readonly ["editor", string];

/**
 * emojiTag
 *
 * Custom emoji resource reference for reactions (NIP-25 / NIP-30)
 */
export type EmojiTag = readonly ["emoji", string, string];

/**
 * Encoding
 */
export type EncodingTag = readonly ["encoding", "base64"];

/**
 * Encryption tag
 *
 * Encryption method supported by wallet service
 */
export type EncryptionTag = readonly ["encryption", string];

/**
 * Encryption algorithm used for the attached file
 */
export type EncryptionAlgorithmTag = readonly ["encryption-algorithm", "aes-gcm"];

export type End_tzidTag = readonly ["end_tzid", string];

export type EndpointTag = readonly ["endpoint", string, ...string[]];

export type EndsTag = readonly ["ends", string, ...string[]];

export type EndsAtTag = readonly ["endsAt", string, ...string[]];

export type ExpirationTag = readonly ["expiration", string];

export type Expires_atTag = readonly ["expires_at", string];

export type FTag = readonly ["f", string];

export type FaTag = readonly ["fa", string, ...string[]];

/**
 * Fallback locations for retrieving the encrypted file
 */
export type FallbackTag = readonly ["fallback", string, ...string[]];

export type FbTag = readonly ["fb", "free" | "busy"];

/**
 * MIME type of the original file before encryption
 */
export type FileTypeTag = readonly ["file-type", string];

export type GTag = readonly ["g", string, ...string[]];

export type GroupTag =
  | readonly ["group", string, string]
  | readonly ["group", string, string, string];

export type HTag = readonly ["h", string];

export type HandTag = readonly ["hand", "1", ...string[]];

/**
 * Repository HEAD reference
 */
export type HeadTag = readonly ["HEAD", string];

/**
 * externalContentIdentifierTag
 *
 * External content identifier tag (NIP-73)
 */
export type ExternalContentITag = readonly ["i", string, string, ...string[]];

/**
 * KeyPackageRef
 */
export type Mip00_iTag = readonly ["i", string];

export type ImageTag = readonly ["image", string, ...string[]];

/**
 * imeta tag
 *
 * NIP-68 metadata describing an image attachment
 */
export type ImetaTag = readonly ["imeta", string, ...string[]];
// Runtime: must contain entries matching: ^url https?://\S+$, ^m (image/(apng|avif|gif|jpeg|png|webp))$, ^url https?://\S+$, ^m (image/(apng|avif|gif|jpeg|png|webp))$

export type UpperKTag = readonly ["k", string];

/**
 * externalContentTypeTag
 *
 * External content type identifier tag (NIP-73)
 */
export type ExternalContentKTag = readonly ["k", string];

export type KTag = readonly ["k", string];

export type Nip69_kTag = readonly ["k", "sell" | "buy"];

/**
 * Label tag (NIP-32). Applies a label within a namespace.
 */
export type LTag = readonly ["l", string, string];

/**
 * Label namespace tag (NIP-32). Second element is namespace or '#<target-tag>' marker.
 */
export type UpperLTag = readonly ["L", string];

export type LayerTag = readonly ["layer", string];

export type LlmTag = readonly ["llm", string, ...string[]];

export type LnurlTag = readonly ["lnurl", string];

export type LocationTag = readonly ["location", string, ...string[]];

export type MTag = readonly ["m", string];

/**
 * Recognized maintainers for the repository
 */
export type MaintainersTag = readonly ["maintainers", string, ...string[]];

export type MemberTag = readonly ["member", string];

export type MergeBaseTag = readonly ["merge-base", string];

export type MergeCommitTag = readonly ["merge-commit", string];

export type MethodTag = readonly ["method", string];

export type MintTag =
  | readonly ["mint", string]
  | readonly ["mint", string, string];

/**
 * MLS Ciphersuite
 */
export type Mls_ciphersuiteTag = readonly ["mls_ciphersuite", string];

/**
 * MLS Extensions
 */
export type Mls_extensionsTag = readonly ["mls_extensions", string, ...string[]];

/**
 * MLS Proposals
 */
export type Mls_proposalsTag = readonly ["mls_proposals", string, ...string[]];

export type Mls_protocol_versionTag = readonly ["mls_protocol_version", string];

export type ModulesTag = readonly ["modules", string];

export type NTag = readonly ["n", "mainnet" | "testnet" | "signet" | "regtest"];

export type NameTag = readonly ["name", string];

export type NetworkTag = readonly ["network", string];

/**
 * Notifications tag
 *
 * Notification types supported by wallet service
 */
export type NotificationsTag = readonly ["notifications", string];

export type NutsTag = readonly ["nuts", string];

export type OptionTag = readonly ["option", string, string, ...string[]];

export type OutputTag = readonly ["output", string];

export type OxTag = readonly ["ox", string];

export type UpperPTag =
  | readonly ["p", string]
  | readonly ["p", string, string];

export type Nip56_pTag = readonly ["p", string, "nudity" | "malware" | "profanity" | "illegal" | "spam" | "impersonation" | "other", ...string[]];

export type PTag =
  | readonly ["p", string]
  | readonly ["p", string, string];

export type Page_rangeTag = readonly ["page_range", string];

export type ParamTag = readonly ["param", string, string, ...string[]];

export type ParentCommitTag = readonly ["parent-commit", string];

export type PathTag = readonly ["path", string, string];

export type PayloadTag = readonly ["payload", string];

export type PinnedTag = readonly ["pinned", string, ...string[]];

export type PmTag = readonly ["pm", string, ...string[]];

export type PolltypeTag = readonly ["polltype", "singlechoice" | "multiplechoice"];

export type PreimageTag = readonly ["preimage", string];

export type PremiumTag = readonly ["premium", string];

export type ProofTag = readonly ["proof", string];

export type PubkeyTag = readonly ["pubkey", string];

export type Published_atTag = readonly ["published_at", string, ...string[]];

export type Published_byTag = readonly ["published_by", string];

export type Published_inTag =
  | readonly ["published_in", string]
  | readonly ["published_in", string, string];

export type Published_onTag = readonly ["published_on", string];

/**
 * Quote tag for quote-reposts (NIP-18). Mirrors NIP-10 e-tag tuple without the mark argument.
Structure: ["q", <event-id or event address>, <relay-url>, <pubkey>?]

 */
export type QTag =
  | readonly ["q", string, string]
  | readonly ["q", string, string, string];

/**
 * Earliest unique commit identifier
 */
export type REucTag = readonly ["r", string, "euc"];

export type RTag =
  | readonly ["r", string]
  | readonly ["r", string, "read" | "write"];

export type RecordingTag = readonly ["recording", string, ...string[]];

/**
 * Git reference state entry
 */
export type GitRefTag = readonly ["ref", string, string, ...string[]];

/**
 * Relay endpoint that issued the NIP-42 authentication challenge
 */
export type AuthRelayTag = readonly ["relay", string];

/**
 * Preferred relay endpoint for receiving direct messages
 */
export type DmRelayTag = readonly ["relay", string];

export type RelayTag = readonly ["relay", string];

export type RelaysTag = readonly ["relays", string, ...string[]];

export type RequestTag = readonly ["request", string];

export type ResponseTag = readonly ["response", string, ...string[]];

export type RoomTag = readonly ["room", string, ...string[]];

export type STag = readonly ["s", "pending" | "canceled" | "in-progress" | "success" | "expired"];

/**
 * Blossom server endpoint advertised by the user
 */
export type ServerTag = readonly ["server", string];

export type ServiceTag = readonly ["service", string, ...string[]];

/**
 * Size of the encrypted file in bytes
 */
export type SizeTag = readonly ["size", string];

export type SourceTag = readonly ["source", string];

export type Start_tzidTag = readonly ["start_tzid", string];

export type StartsTag = readonly ["starts", string, ...string[]];

export type StatusLiveTag = readonly ["status", "planned" | "live" | "ended", ...string[]];

export type StatusRoomTag = readonly ["status", "open" | "private" | "closed", ...string[]];

export type StatusTag = readonly ["status", "accepted" | "declined" | "tentative"];

export type StreamingTag = readonly ["streaming", string, ...string[]];

/**
 * Conversation subject for a private room
 */
export type SubjectTag = readonly ["subject", string];

export type SummaryTag = readonly ["summary", string, ...string[]];

export type TTag = readonly ["t", string, ...string[]];

/**
 * Thumbnail URL for the encrypted media
 */
export type ThumbTag = readonly ["thumb", string];

export type TitleTag = readonly ["title", string, ...string[]];

export type Total_participantsTag = readonly ["total_participants", string, ...string[]];

export type UTag = readonly ["u", string];

export type UrlTag = readonly ["url", string];

export type VersionTag = readonly ["version", string];

/**
 * Repository browsing URLs
 */
export type WebTag = readonly ["web", string, ...string[]];

export type WordTag = readonly ["word", string];

export type Nip56_xTag = readonly ["x", string, "nudity" | "malware" | "profanity" | "illegal" | "spam" | "impersonation" | "other", ...string[]];

/**
 * Checksum of the encrypted file
 */
export type XTag = readonly ["x", string];

export type YTag = readonly ["y", string];

export type ZTag = readonly ["z", "order"];
