import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { emitBuildersFile } from '../src/emit-builders.js';
import type { KindShape, TagRequirement } from '../src/kind-types.js';

// --- Helpers ---

function makeReq(tagName: string, opts?: Partial<TagRequirement>): TagRequirement {
  return {
    tagName,
    positions: [
      { index: 0, required: true, constValue: tagName, type: 'string' },
      { index: 1, required: true, type: 'string' },
    ],
    minItems: 2,
    maxItems: 2,
    additionalItems: false,
    ...opts,
  };
}

function makeShape(kindNumber: number, overrides?: Partial<KindShape>): KindShape {
  return {
    kindNumber,
    nip: 'nip-01',
    requiredTags: [],
    perItemConditionals: [],
    arrayLevelConditionals: [],
    anyOfTagGroups: [],
    category: 'bare',
    ...overrides,
  };
}

// --- emitBuildersFile ---

describe('emitBuildersFile', () => {
  it('emits header', () => {
    const output = emitBuildersFile([makeShape(1)]);
    assert.ok(output.startsWith('// Auto-generated by @nostrability/schemata-codegen'));
  });

  it('skips bare kinds', () => {
    const output = emitBuildersFile([makeShape(1), makeShape(2)]);
    assert.ok(!output.includes('buildKind1Tags'));
    assert.ok(!output.includes('buildKind2Tags'));
  });

  it('generates interface for simple required tag', () => {
    const shapes = [makeShape(30023, {
      requiredTags: [makeReq('d')],
      category: 'simple-contains',
    })];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('export interface Kind30023TagsInput'));
    assert.ok(output.includes('d: string'));
  });

  it('generates function for simple required tag', () => {
    const shapes = [makeShape(30023, {
      requiredTags: [makeReq('d')],
      category: 'simple-contains',
    })];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('export function buildKind30023Tags'));
    assert.ok(output.includes('tags.push(["d", data.d])'));
  });

  it('marks optional tags with ? in interface', () => {
    const shapes = [makeShape(7, {
      anyOfTagGroups: [{
        requirements: [makeReq('e'), makeReq('a')],
      }],
      category: 'conditional',
    })];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('a?: string'));
    assert.ok(output.includes('e?: string'));
  });

  it('wraps optional tags in if !== undefined', () => {
    const shapes = [makeShape(7, {
      anyOfTagGroups: [{
        requirements: [makeReq('e')],
      }],
      category: 'conditional',
    })];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('if (data.e !== undefined)'));
  });

  it('generates object interface for multi-position tags', () => {
    const shapes = [makeShape(10002, {
      requiredTags: [makeReq('r', {
        positions: [
          { index: 0, required: true, constValue: 'r', type: 'string' },
          { index: 1, required: true, type: 'string', title: 'relay URL' },
          { index: 2, required: false, type: 'string', enumValues: ['read', 'write'], title: 'marker' },
        ],
        minItems: 2,
        maxItems: 3,
        additionalItems: false,
      })],
      category: 'simple-contains',
    })];
    const output = emitBuildersFile(shapes);
    // Should have object type with sub-fields
    assert.ok(output.includes('r: {'));
    assert.ok(output.includes('relayUrl: string'));
    assert.ok(output.includes('marker?:'));
  });

  it('generates sequential if guards for optional trailing positions', () => {
    const shapes = [makeShape(10002, {
      requiredTags: [makeReq('r', {
        positions: [
          { index: 0, required: true, constValue: 'r', type: 'string' },
          { index: 1, required: true, type: 'string', title: 'relay URL' },
          { index: 2, required: false, type: 'string', enumValues: ['read', 'write'], title: 'marker' },
        ],
        minItems: 2,
        maxItems: 3,
        additionalItems: false,
      })],
      category: 'simple-contains',
    })];
    const output = emitBuildersFile(shapes);
    // Should build tag incrementally with if guard for optional position
    assert.ok(output.includes('const t0: string[]'));
    assert.ok(output.includes('if (data.r.marker !== undefined) t0.push(data.r.marker)'));
    assert.ok(output.includes('tags.push(t0)'));
  });

  it('generates enum type in interface', () => {
    const shapes = [makeShape(100, {
      requiredTags: [makeReq('status', {
        positions: [
          { index: 0, required: true, constValue: 'status', type: 'string' },
          { index: 1, required: true, type: 'string', enumValues: ['active', 'inactive'] },
        ],
      })],
      category: 'simple-contains',
    })];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('"active" | "inactive"'));
  });

  it('generates dispatch function', () => {
    const shapes = [
      makeShape(30023, {
        requiredTags: [makeReq('d')],
        category: 'simple-contains',
      }),
      makeShape(10002, {
        requiredTags: [makeReq('r')],
        category: 'simple-contains',
      }),
    ];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('export function buildKindTags'));
    assert.ok(output.includes('case 10002:'));
    assert.ok(output.includes('case 30023:'));
  });

  it('exports BUILDER_KINDS', () => {
    const shapes = [
      makeShape(30023, {
        requiredTags: [makeReq('d')],
        category: 'simple-contains',
      }),
    ];
    const output = emitBuildersFile(shapes);
    assert.ok(output.includes('export const BUILDER_KINDS'));
    assert.ok(output.includes('30023'));
  });

  it('sorts kinds numerically', () => {
    const shapes = [
      makeShape(30023, { requiredTags: [makeReq('d')], category: 'simple-contains' }),
      makeShape(7, { requiredTags: [makeReq('e')], category: 'simple-contains' }),
      makeShape(10002, { requiredTags: [makeReq('r')], category: 'simple-contains' }),
    ];
    const output = emitBuildersFile(shapes);
    const fnPositions = [
      output.indexOf('buildKind7Tags'),
      output.indexOf('buildKind10002Tags'),
      output.indexOf('buildKind30023Tags'),
    ];
    assert.ok(fnPositions[0] < fnPositions[1]);
    assert.ok(fnPositions[1] < fnPositions[2]);
  });

  it('handles mixed required and optional tags', () => {
    const shapes = [makeShape(30023, {
      requiredTags: [makeReq('d')],
      perItemConditionals: [{
        conditionTagName: 't',
        requirement: makeReq('t'),
      }],
      category: 'conditional',
    })];
    const output = emitBuildersFile(shapes);
    // d should be required, t should be optional
    assert.ok(output.includes('d: string'));
    assert.ok(output.includes('t?: string'));
  });
});
