/**
 * Kind registry emitter: KindShape[] → kind-registry.ts
 *
 * Generates a runtime registry with structured metadata per kind:
 *   - KindMeta interface with kind number, NIP, name, tags, category
 *   - KIND_REGISTRY record keyed by kind number
 *   - KIND_NAMES record for human-readable display
 */

import type { KindShape } from './kind-types.js';

/**
 * Build a human-readable name from a KindShape.
 * Prefers description (most schemas have good ones), falls back to title
 * (if not just "kindN"), falls back to "Kind N (NIP-XX)".
 */
function kindDisplayName(shape: KindShape): string {
  const nipLabel = shape.nip.replace(/^nip-/, 'NIP-');

  // Prefer description — most schemas have descriptive ones
  if (shape.description) {
    // Extract the short name from descriptions like "NIP-57 Zap Receipt event"
    let name = shape.description
      .replace(/\s*\([^)]*\)\s*/g, ' ')     // strip parentheticals
      .replace(/\bevent\b/gi, '')            // strip "event"
      .replace(/\bdefined by\b.*$/i, '')     // strip "defined by NIP-XX"
      .replace(/\bNIP-\d+[A-Z]?\b/gi, '')   // strip NIP labels
      .replace(/\bCEP-\d+\b/gi, '')         // strip CEP labels
      .replace(/\bkind\s*\d+\b/gi, '')       // strip "kind N"
      .replace(/\s+/g, ' ')                  // normalize whitespace
      .trim();
    // Strip leading/trailing punctuation
    name = name.replace(/^[.,\-—:]+\s*/, '').replace(/\s*[.,\-—:]+$/, '');
    if (name) return `${name} (${nipLabel})`;
  }

  // Fall back to title if it's not just "kindN"
  if (shape.title && !/^kind\d+$/i.test(shape.title)) {
    const name = shape.title
      .replace(/\(kind\s*\d+\)/gi, '')       // strip "(kind N)" suffix
      .replace(/\bNIP-\d+[A-Z]?\b/gi, '')   // strip NIP labels
      .replace(/\s+/g, ' ')
      .trim();
    if (name) return `${name} (${nipLabel})`;
  }

  return `Kind ${shape.kindNumber} (${nipLabel})`;
}

/**
 * Emit the complete kind-registry.ts file.
 */
export function emitRegistryFile(shapes: KindShape[]): string {
  const sorted = [...shapes].sort((a, b) => a.kindNumber - b.kindNumber);

  const lines: string[] = [
    '// Auto-generated by @nostrability/schemata-codegen',
    '// Do not edit manually.',
    '//',
    '// Structured metadata for all Nostr event kinds with schemata schemas',
    '',
    'export interface KindMeta {',
    '  kind: number;',
    '  nip: string;',
    '  name: string;',
    '  description?: string;',
    '  requiredTags: string[];',
    '  hasConditionals: boolean;',
    '  category: "bare" | "simple-contains" | "multi-contains" | "conditional" | "failed";',
    '}',
    '',
  ];

  // Pre-compute display names once
  const displayNames = new Map<number, string>();
  for (const shape of sorted) {
    displayNames.set(shape.kindNumber, kindDisplayName(shape));
  }

  // KIND_REGISTRY
  lines.push('export const KIND_REGISTRY: Record<number, KindMeta> = {');
  for (const shape of sorted) {
    const name = displayNames.get(shape.kindNumber)!;
    const requiredTags = shape.requiredTags.map(t => t.tagName);
    const hasConditionals = shape.perItemConditionals.length > 0 || shape.arrayLevelConditionals.length > 0;

    lines.push(`  ${shape.kindNumber}: {`);
    lines.push(`    kind: ${shape.kindNumber},`);
    lines.push(`    nip: ${JSON.stringify(shape.nip)},`);
    lines.push(`    name: ${JSON.stringify(name)},`);
    if (shape.description) {
      lines.push(`    description: ${JSON.stringify(shape.description)},`);
    }
    lines.push(`    requiredTags: ${JSON.stringify(requiredTags)},`);
    lines.push(`    hasConditionals: ${hasConditionals},`);
    lines.push(`    category: ${JSON.stringify(shape.category)},`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  // KIND_NAMES — flat Record<number, string> for easy display
  lines.push('export const KIND_NAMES: Record<number, string> = {');
  for (const shape of sorted) {
    lines.push(`  ${shape.kindNumber}: ${JSON.stringify(displayNames.get(shape.kindNumber)!)},`);
  }
  lines.push('};');
  lines.push('');

  // KNOWN_KIND_NUMBERS — sorted array for iteration
  lines.push(`export const KNOWN_KIND_NUMBERS: readonly number[] = [`);
  const chunks: string[] = [];
  let chunk: number[] = [];
  for (const shape of sorted) {
    chunk.push(shape.kindNumber);
    if (chunk.length >= 10) {
      chunks.push('  ' + chunk.join(', ') + ',');
      chunk = [];
    }
  }
  if (chunk.length > 0) {
    chunks.push('  ' + chunk.join(', ') + ',');
  }
  lines.push(chunks.join('\n'));
  lines.push('];');
  lines.push('');

  return lines.join('\n');
}
