/**
 * Error message map emitter: raw kind schemas → error-messages.ts
 *
 * Extracts all errorMessage fields from schemata kind schemas and generates
 * a lookup table. Separates base event messages (shared across all kinds)
 * from kind-specific messages.
 *
 * Output format:
 *   BASE_ERROR_MESSAGES: Record<string, string>  — field-level messages common to all kinds
 *   KIND_ERROR_MESSAGES: Record<number, KindErrorEntry[]>  — per-kind messages
 */

import { readFileSync } from 'node:fs';

interface ErrorEntry {
  keyword: string;
  message: string;
}

/** Base event field messages that appear in every schema. Canonical source of truth. */
const BASE_ENTRIES: [string, string][] = [
  ['content', 'content must be a string'],
  ['created_at', 'created_at must be a timestamp expressed in seconds (not milliseconds)'],
  ['id', 'id must be a valid hash'],
  ['pubkey', 'pubkey must be a secp256k1 public key'],
  ['sig', 'sig must be 128 lowercase hex characters (64 bytes)'],
  ['tags', 'tags must be an array of valid tag tuples'],
];
const BASE_MESSAGES = new Set(BASE_ENTRIES.map(([, msg]) => msg));

/**
 * Recursively collect errorMessage fields from a schema object.
 */
function collectErrorMessages(obj: unknown, path: string = ''): ErrorEntry[] {
  const entries: ErrorEntry[] = [];

  if (typeof obj !== 'object' || obj === null) return entries;
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i++) {
      entries.push(...collectErrorMessages(obj[i], `${path}[${i}]`));
    }
    return entries;
  }

  const record = obj as Record<string, unknown>;
  if ('errorMessage' in record) {
    const em = record['errorMessage'];
    if (typeof em === 'string') {
      entries.push({ keyword: path || 'root', message: em });
    } else if (typeof em === 'object' && em !== null && !Array.isArray(em)) {
      for (const [kw, msg] of Object.entries(em as Record<string, string>)) {
        if (typeof msg === 'string') {
          entries.push({ keyword: kw, message: msg });
        }
      }
    }
  }

  for (const [key, value] of Object.entries(record)) {
    if (key !== 'errorMessage') {
      entries.push(...collectErrorMessages(value, path ? `${path}.${key}` : key));
    }
  }

  return entries;
}

/**
 * Extract error messages from a kind schema file.
 * Returns only non-base (kind-specific) messages.
 */
export function extractErrorMessages(filePath: string): ErrorEntry[] {
  const raw = readFileSync(filePath, 'utf-8');
  const schema = JSON.parse(raw);
  const all = collectErrorMessages(schema);
  return all.filter(e => !BASE_MESSAGES.has(e.message));
}

/**
 * Emit the complete error-messages.ts file.
 */
export function emitErrorMessagesFile(
  kindMessages: Map<number, ErrorEntry[]>,
): string {
  const lines: string[] = [
    '// Auto-generated by @nostrability/schemata-codegen',
    '// Do not edit manually.',
    '//',
    '// Human-readable error messages extracted from schemata schemas.',
    '// Use these to provide friendly error descriptions without the ajv-errors plugin.',
    '',
    'export interface KindErrorEntry {',
    '  keyword: string;',
    '  message: string;',
    '}',
    '',
  ];

  // Base messages (common to all event schemas)
  lines.push('export const BASE_ERROR_MESSAGES: Record<string, string> = {');
  for (const [field, msg] of BASE_ENTRIES) {
    lines.push(`  ${JSON.stringify(field)}: ${JSON.stringify(msg)},`);
  }
  lines.push('};');
  lines.push('');

  // Per-kind messages
  const sorted = [...kindMessages.entries()]
    .filter(([_, entries]) => entries.length > 0)
    .sort(([a], [b]) => a - b);

  lines.push('export const KIND_ERROR_MESSAGES: Record<number, KindErrorEntry[]> = {');
  for (const [kind, entries] of sorted) {
    // Deduplicate by message
    const seen = new Set<string>();
    const unique = entries.filter(e => {
      if (seen.has(e.message)) return false;
      seen.add(e.message);
      return true;
    });

    lines.push(`  ${kind}: [`);
    for (const entry of unique) {
      lines.push(`    { keyword: ${JSON.stringify(entry.keyword)}, message: ${JSON.stringify(entry.message)} },`);
    }
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
