/**
 * TypeScript emitter: KindShape → kinds.d.ts
 *
 * Generates:
 *   - Per-kind interface with literal `kind` discriminant
 *   - JSDoc with required/conditional tag documentation
 *   - Discriminated union type: NostrEvent
 *   - KNOWN_KINDS constant mapping
 */

import type { KindShape, TagRequirement, PerItemConditional, ArrayLevelConditional } from './kind-types.js';

/**
 * Convert a kind number to a PascalCase interface name.
 * e.g., 0 → "Kind0Event", 10002 → "Kind10002Event"
 */
export function kindInterfaceName(kindNumber: number): string {
  return `Kind${kindNumber}Event`;
}

/**
 * Emit JSDoc for a kind interface.
 */
function emitKindJSDoc(shape: KindShape): string {
  const lines: string[] = ['/**'];

  if (shape.title) {
    lines.push(` * ${shape.title}`);
  }
  if (shape.description && shape.description !== shape.title) {
    if (shape.title) lines.push(' *');
    lines.push(` * ${shape.description}`);
  }

  lines.push(` * @nip ${shape.nip}`);

  if (shape.requiredTags.length > 0) {
    lines.push(' *');
    lines.push(' * Required tags:');
    for (const tag of shape.requiredTags) {
      const posInfo = tag.positions.length > 1
        ? ` (${tag.minItems}${tag.maxItems ? '-' + tag.maxItems : '+'} items)`
        : '';
      const errInfo = tag.errorMessage ? ` — ${tag.errorMessage}` : '';
      lines.push(` *   - \`${tag.tagName}\`${posInfo}${errInfo}`);
    }
  }

  if (shape.perItemConditionals.length > 0 || shape.arrayLevelConditionals.length > 0) {
    lines.push(' *');
    lines.push(' * Conditional tags:');
    for (const cond of shape.perItemConditionals) {
      lines.push(` *   - If tag is \`${cond.conditionTagName}\`, must match ${cond.requirement.tagName} schema`);
    }
    for (const cond of shape.arrayLevelConditionals) {
      const errInfo = cond.errorMessage ? ` — ${cond.errorMessage}` : '';
      lines.push(` *   - If tags contain \`${cond.conditionTagName}\`, must also contain valid \`${cond.requirement.tagName}\`${errInfo}`);
    }
  }

  lines.push(' */');
  return lines.join('\n');
}

/**
 * Emit a single kind interface.
 */
function emitKindInterface(shape: KindShape): string {
  const name = kindInterfaceName(shape.kindNumber);
  const doc = emitKindJSDoc(shape);

  const lines: string[] = [];
  lines.push(doc);
  lines.push(`export interface ${name} {`);
  lines.push(`  readonly kind: ${shape.kindNumber};`);
  lines.push('  readonly content: string;');
  lines.push('  readonly created_at: number;');
  lines.push('  readonly id: string;');
  lines.push('  readonly pubkey: string;');
  lines.push('  readonly sig: string;');
  lines.push('  readonly tags: ReadonlyArray<readonly string[]>;');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Emit the complete kinds.d.ts file from multiple KindShapes.
 */
export function emitKindsFile(shapes: KindShape[]): string {
  const sorted = [...shapes].sort((a, b) => a.kindNumber - b.kindNumber);

  const header = [
    '// Auto-generated by @nostrability/schemata-codegen',
    '// Do not edit manually.',
    '//',
    `// Generated from ${sorted.length} kind schemas`,
    '',
  ].join('\n');

  // Per-kind interfaces
  const interfaces = sorted.map(s => emitKindInterface(s)).join('\n\n');

  // Discriminated union
  const unionMembers = sorted.map(s => kindInterfaceName(s.kindNumber));
  const union = [
    '',
    '/** Discriminated union of all known Nostr event kinds */',
    `export type NostrEvent =`,
    ...unionMembers.map((name, i) => `  | ${name}${i === unionMembers.length - 1 ? ';' : ''}`),
  ].join('\n');

  // KNOWN_KINDS mapping
  const kindEntries = sorted.map(s => {
    const label = s.title ?? `kind${s.kindNumber}`;
    return `  ${s.kindNumber}: ${JSON.stringify(label)},`;
  });
  const kindsMap = [
    '',
    '/** Mapping of known kind numbers to their labels */',
    'export declare const KNOWN_KINDS: {',
    ...kindEntries,
    '};',
  ].join('\n');

  return header + interfaces + '\n' + union + '\n' + kindsMap + '\n';
}
